# -*- coding: utf-8 -*-
"""
Django settings for VENDO_SRI project with OAuth support.
Sistema de Facturación SRI - Configuración con Autenticación OAuth

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SECURITY SETTINGS
# ==========================================

SECRET_KEY = config('SECRET_KEY', default='django-insecure-vendo-sri-change-this-in-production')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0').split(',')

# ==========================================
# APPLICATION DEFINITION
# ==========================================

# Django core apps
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Requerido para allauth
]

# Third party apps
THIRD_PARTY_APPS = [
    # API
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    # Forms
    'crispy_forms',
    'crispy_bootstrap5',
    
    # OAuth & Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Local apps
LOCAL_APPS = [
    'apps.core',
    'apps.users',
    'apps.companies',
    'apps.certificates',
    'apps.invoicing',
    'apps.notifications',
    'apps.settings',
    'apps.sri_integration',
    'apps.api',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ==========================================
# MIDDLEWARE CONFIGURATION
# ==========================================

# ==========================================
# MIDDLEWARE CONFIGURATION
# ==========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requerido para allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # NUEVO: Middleware para control de acceso y sala de espera
    'apps.users.views.CheckUserAccessMiddleware',
]

ROOT_URLCONF = 'vendo_sri.urls'

# ==========================================
# SITES FRAMEWORK (REQUERIDO PARA ALLAUTH)
# ==========================================

SITE_ID = 1

# ==========================================
# AUTHENTICATION CONFIGURATION
# ==========================================

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Django backends
    'django.contrib.auth.backends.ModelBackend',
    
    # Allauth backends
    'allauth.account.auth_backends.AuthenticationBackend',
]

# URLs de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ==========================================
# ALLAUTH CONFIGURATION
# ==========================================

# Configuración de cuentas
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True

# URLs personalizadas
ACCOUNT_LOGIN_URL = '/accounts/login/'
ACCOUNT_LOGOUT_URL = '/accounts/logout/'
ACCOUNT_SIGNUP_URL = '/accounts/signup/'

# Rate limiting
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',
    'signup': '20/h',
}

# Configuración de cuentas sociales
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Providers de OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2',
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
        }
    }
}

# ==========================================
# TEMPLATES CONFIGURATION
# ==========================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendo_sri.wsgi.application'

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='vendo_sri'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'options': '-c search_path=public',
        },
    }
}

# ==========================================
# USER MODEL CONFIGURATION
# ==========================================

AUTH_USER_MODEL = 'users.User'

# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# ==========================================
# STATIC FILES CONFIGURATION
# ==========================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ==========================================
# MEDIA FILES CONFIGURATION
# ==========================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'storage')

# ==========================================
# DEFAULT AUTO FIELD
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# REST FRAMEWORK CONFIGURATION
# ==========================================

REST_FRAMEWORK = {\
    "DEFAULT_AUTHENTICATION_CLASSES": [\
        "rest_framework.authentication.SessionAuthentication",\
        "rest_framework.authentication.TokenAuthentication",\
    ],\
    "DEFAULT_PERMISSION_CLASSES": [\
        "rest_framework.permissions.IsAuthenticated",\
    ],\
    "DEFAULT_RENDERER_CLASSES": [\
        "rest_framework.renderers.JSONRenderer",\
        "rest_framework.renderers.BrowsableAPIRenderer",\
    ],\
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",\
    "PAGE_SIZE": 25,\
    "DEFAULT_FILTER_BACKENDS": [\
        "django_filters.rest_framework.DjangoFilterBackend",\
        "rest_framework.filters.SearchFilter",\
        "rest_framework.filters.OrderingFilter",\
    ],\
    "DEFAULT_THROTTLE_CLASSES": [\
        "rest_framework.throttling.AnonRateThrottle",\
        "rest_framework.throttling.UserRateThrottle"\
    ],\
    "DEFAULT_THROTTLE_RATES": {\
        "anon": "100/day",\
        "user": "1000/day"\
    }\
}

# ==========================================
# CORS CONFIGURATION
# ==========================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# ==========================================
# CRISPY FORMS CONFIGURATION
# ==========================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ==========================================
# MESSAGE TAGS FOR BOOTSTRAP
# ==========================================

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ==========================================
# EMAIL CONFIGURATION
# ==========================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desarrollo
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@vendo-sri.com')

# ==========================================
# SRI CONFIGURATION
# ==========================================

SRI_AMBIENTE = config('SRI_AMBIENTE', default='1')  # 1=Pruebas, 2=Producción
SRI_TIPO_EMISION = config('SRI_TIPO_EMISION', default='1')  # 1=Normal
SRI_TIMEOUT = config('SRI_TIMEOUT', default=30, cast=int)

# URLs SRI según ambiente
SRI_URLS = {
    '1': {  # Pruebas
        'recepcion': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'autorizacion': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'
    },
    '2': {  # Producción
        'recepcion': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'autorizacion': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'
    }
}

# ==========================================
# DEVELOPMENT SETTINGS
# ==========================================

if DEBUG:
    # Add development apps if available
    try:
        import debug_toolbar
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1', 'localhost']
    except ImportError:
        pass
    
    # CORS allow all in development
    CORS_ALLOW_ALL_ORIGINS = True

# ==========================================
# LOGGING CONFIGURATION
# ==========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/vendo_sri.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Crear directorio de logs
import os
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

print("✅ Settings VENDO_SRI configurado con OAuth")
print(f"DEBUG: {DEBUG}")
print(f"SITE_ID: {SITE_ID}")
print(f"AUTH_USER_MODEL: {AUTH_USER_MODEL}")