# -*- coding: utf-8 -*-
"""
Django settings for VENDO_SRI project with OAuth support.
Sistema de Facturación SRI - Configuración con Autenticación OAuth
ACTUALIZADO con GlobalCertificateManager y Token Authentication

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SECURITY SETTINGS
# ==========================================

SECRET_KEY = config('SECRET_KEY', default='django-insecure-vendo-sri-change-this-in-production')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0').split(',')

# ==========================================
# APPLICATION DEFINITION
# ==========================================

# Django core apps
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  
]

# Third party apps
THIRD_PARTY_APPS = [
    # API
    'rest_framework',
    'rest_framework.authtoken',  # AGREGADO PARA TOKEN AUTHENTICATION 
    'corsheaders',
    'django_filters',
    
    # Forms
    'crispy_forms',
    'crispy_bootstrap5',
    
    # OAuth & Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Local apps
LOCAL_APPS = [
    'apps.core',
    'apps.users',
    'apps.companies',
    'apps.certificates',
    'apps.invoicing',
    'apps.notifications',
    'apps.settings',
    'apps.sri_integration',
    'apps.api',
    'apps.billing',
    'apps.custom_admin',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ==========================================
# MIDDLEWARE CONFIGURATION
# ==========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requerido para allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.billing.middleware.BillingLimitMiddleware',
    # SOLO ESTOS DOS:
    'apps.users.views.SimpleSessionTimeoutMiddleware',  # Para timeout
    'apps.users.views.CheckUserAccessMiddleware',       # Para sala de espera
    'apps.api.permissions.CompanySecurityMiddleware',
    'apps.core.middleware.DashboardSecurityMiddleware',
]

ROOT_URLCONF = 'vendo_sri.urls'

# ==========================================
# SITES FRAMEWORK (REQUERIDO PARA ALLAUTH)
# ==========================================

SITE_ID = 1

# ==========================================
# AUTHENTICATION CONFIGURATION
# ==========================================

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Django backends
    'django.contrib.auth.backends.ModelBackend',
    
    # Allauth backends
    'allauth.account.auth_backends.AuthenticationBackend',
]

# URLs de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ==========================================
# ALLAUTH CONFIGURATION
# ==========================================

# Configuración de cuentas
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True

# URLs personalizadas
ACCOUNT_LOGIN_URL = '/accounts/login/'
ACCOUNT_LOGOUT_URL = '/accounts/logout/'
ACCOUNT_SIGNUP_URL = '/accounts/signup/'

# Rate limiting
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',
    'signup': '20/h',
}

# Configuración de cuentas sociales
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Providers de OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2',
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
        }
    }
}

# ==========================================
# TEMPLATES CONFIGURATION
# ==========================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendo_sri.wsgi.application'

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='vendo_sri'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'options': '-c search_path=public',
        },
    }
}

# ==========================================
# USER MODEL CONFIGURATION
# ==========================================

AUTH_USER_MODEL = 'users.User'

# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# ==========================================
# STATIC FILES CONFIGURATION
# ==========================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ==========================================
# MEDIA FILES CONFIGURATION
# ==========================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'storage')

# ==========================================
# DEFAULT AUTO FIELD
# ==========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# REST FRAMEWORK CONFIGURATION CON TOKEN
# ==========================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.api.authentication.DualTokenAuthentication",  # Authentication Dual
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day"
    }
}

# ==========================================
# TOKEN AUTHENTICATION SETTINGS
# ==========================================

# Configuración automática de tokens
AUTO_CREATE_TOKENS = config('AUTO_CREATE_TOKENS', default=True, cast=bool)

# Token expiration (opcional - por defecto DRF no expira tokens)
TOKEN_EXPIRES = config('TOKEN_EXPIRES', default=None)  # None = no expira

# Regenerar token automáticamente en login
AUTO_REGENERATE_TOKEN_ON_LOGIN = config('AUTO_REGENERATE_TOKEN', default=False, cast=bool)

# ==========================================
# CORS CONFIGURATION
# ==========================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# Headers permitidos para API calls con token
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # Headers para token authentication
    'x-api-key',
    'x-auth-token',
]

# ==========================================
# CRISPY FORMS CONFIGURATION
# ==========================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ==========================================
# MESSAGE TAGS FOR BOOTSTRAP
# ==========================================

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ==========================================
# EMAIL CONFIGURATION
# ==========================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desarrollo
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@vendo-sri.com')

# ==========================================
# SRI CONFIGURATION
# ==========================================

SRI_AMBIENTE = config('SRI_AMBIENTE', default='1')  # 1=Pruebas, 2=Producción
SRI_TIPO_EMISION = config('SRI_TIPO_EMISION', default='1')  # 1=Normal
SRI_TIMEOUT = config('SRI_TIMEOUT', default=30, cast=int)

# URLs SRI según ambiente
SRI_URLS = {
    '1': {  # Pruebas
        'recepcion': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'autorizacion': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'
    },
    '2': {  # Producción
        'recepcion': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'autorizacion': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'
    }
}

# ==========================================
# SESSION CONFIGURATION - Cierre por inactividad
# ==========================================

# Duración de la sesión en segundos (1 hora = 3600 segundos)
SESSION_COOKIE_AGE = 3600  # 1 hora

# La sesión expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Guardar la sesión en cada request (actualiza el tiempo de expiración)
SESSION_SAVE_EVERY_REQUEST = True

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'vendo_sri_sessionid'

# Seguridad de cookies
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS en producción
SESSION_COOKIE_HTTPONLY = True  # No accesible via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'

# Tiempo de advertencia antes del cierre (en segundos)
SESSION_TIMEOUT_WARNING = 300  # 5 minutos antes

# Backend de sesiones (usar base de datos para mayor control)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ==========================================
# GlobalCertificateManager CONFIGURATION
# ==========================================

# Configuración del sistema de gestión de certificados
CERTIFICATE_CACHE_TIMEOUT = config('CERTIFICATE_CACHE_TIMEOUT', default=3600, cast=int)  # 1 hora
MAX_CERTIFICATES_CACHE = config('MAX_CERTIFICATES_CACHE', default=1000, cast=int)
CERTIFICATE_CLEANUP_INTERVAL = config('CERTIFICATE_CLEANUP_INTERVAL', default=300, cast=int)  # 5 minutos

# Auto-precarga de certificados al iniciar la aplicación
CERTIFICATE_AUTO_PRELOAD = config('CERTIFICATE_AUTO_PRELOAD', default=True, cast=bool)
CERTIFICATE_AUTO_PRELOAD_DELAY = config('CERTIFICATE_AUTO_PRELOAD_DELAY', default=2, cast=int)  # segundos

# Auto-limpieza de certificados expirados
CERTIFICATE_AUTO_CLEANUP = config('CERTIFICATE_AUTO_CLEANUP', default=True, cast=bool)

# Configuración de validación de certificados
CERTIFICATE_VALIDATION_RULES = {
    'min_days_before_expiration_warning': 30,
    'max_certificate_file_size': 10 * 1024 * 1024,  # 10 MB
    'allowed_certificate_formats': ['.p12', '.pfx'],
    'require_password': True,
}

# Configuración de seguridad para certificados
CERTIFICATE_ENCRYPTION_ALGORITHM = 'AES-256-GCM'
CERTIFICATE_KEY_DERIVATION = 'PBKDF2'

# Métricas y monitoreo
CERTIFICATE_METRICS_ENABLED = config('CERTIFICATE_METRICS_ENABLED', default=True, cast=bool)
CERTIFICATE_USAGE_LOGGING = config('CERTIFICATE_USAGE_LOGGING', default=True, cast=bool)

# Configuración de alertas por email
CERTIFICATE_ALERTS = {
    'email_on_expiration': config('CERTIFICATE_EMAIL_ALERTS', default=True, cast=bool),
    'email_on_load_failure': True,
    'days_before_expiration_alert': [30, 7, 1],  # Alertas 30, 7 y 1 día antes
}

# Email para alertas de certificados
CERTIFICATE_ALERT_EMAIL = config('CERTIFICATE_ALERT_EMAIL', default=EMAIL_HOST_USER)

# Configuración de archivos de certificados
SECURE_FILE_UPLOAD_PERMISSIONS = 0o600  # Solo lectura/escritura para el propietario
CERTIFICATE_STORAGE_PERMISSIONS = 0o600

# Configuración por defecto para comandos de gestión
CERTIFICATE_PRELOAD_DEFAULTS = {
    'force_reload': False,
    'validate_only': False,
    'clear_cache_before': False,
    'show_stats_after': True,
}

# ==========================================
# SRI TIMEOUTS Y CONFIGURACIÓN AVANZADA
# ==========================================

# Configuración de timeouts para SRI (actualizada)
SRI_TIMEOUTS = {
    'connection_timeout': config('SRI_CONNECTION_TIMEOUT', default=30, cast=int),
    'read_timeout': config('SRI_READ_TIMEOUT', default=60, cast=int),
    'authorization_max_attempts': config('SRI_AUTH_MAX_ATTEMPTS', default=10, cast=int),
    'authorization_wait_seconds': config('SRI_AUTH_WAIT_SECONDS', default=30, cast=int),
}

# URLs del SRI actualizadas con configuración de ambientes
SRI_URLS_COMPLETE = {
    'PRODUCTION': {
        'reception': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'authorization': 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl',
    },
    'TEST': {
        'reception': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl',
        'authorization': 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl',
    }
}

# ==========================================
# CACHE CONFIGURATION
# ==========================================

# Cache para certificados (opcional, además del cache en memoria)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'vendo-sri-cache',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    },
    'certificates': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'certificates-cache',
        'TIMEOUT': CERTIFICATE_CACHE_TIMEOUT,
        'OPTIONS': {
            'MAX_ENTRIES': MAX_CERTIFICATES_CACHE,
        }
    }
}

# Si Redis está disponible, usarlo en producción
if not DEBUG and config('REDIS_URL', default=''):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        },
        'certificates': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/2'),
            'TIMEOUT': CERTIFICATE_CACHE_TIMEOUT,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# ==========================================
# DEVELOPMENT SETTINGS
# ==========================================

if DEBUG:
    # Add development apps if available
    try:
        import debug_toolbar
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1', 'localhost']
    except ImportError:
        pass
    
    # CORS allow all in development
    CORS_ALLOW_ALL_ORIGINS = True
    
    # Configuración de certificados más permisiva en desarrollo
    CERTIFICATE_CACHE_TIMEOUT = 1800  # 30 minutos
    MAX_CERTIFICATES_CACHE = 100
    CERTIFICATE_AUTO_PRELOAD_DELAY = 1

# ==========================================
# PRODUCTION SETTINGS
# ==========================================

# Configuración específica para producción
if not DEBUG:
    # Configuración de certificados optimizada para producción
    CERTIFICATE_CACHE_TIMEOUT = 7200  # 2 horas
    MAX_CERTIFICATES_CACHE = 5000
    CERTIFICATE_AUTO_PRELOAD_DELAY = 5
    
    # Seguridad adicional en producción
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# ==========================================
# LOGGING CONFIGURATION - ACTUALIZADA
# ==========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'certificates': {
            'format': '[CERTIFICATES] {asctime} {levelname}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'sri_integration': {
            'format': '[SRI] {asctime} {levelname}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/vendo_sri.log',
            'formatter': 'verbose',
        },
        'certificates_file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/certificates.log',
            'formatter': 'certificates',
            'level': 'INFO',
        },
        'certificates_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'certificates',
            'level': 'INFO',
        },
        'sri_file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/sri_integration.log',
            'formatter': 'sri_integration',
            'level': 'INFO',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.certificates': {
            'handlers': ['certificates_file', 'certificates_console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'apps.sri_integration.services.global_certificate_manager': {
            'handlers': ['certificates_file', 'certificates_console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'apps.sri_integration.services.document_processor': {
            'handlers': ['sri_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.api.views.sri_views': {
            'handlers': ['sri_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==========================================
# CELERY CONFIGURATION (OPCIONAL)
# ==========================================

# Si usas Celery para tareas en background
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Tareas periódicas para certificados
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-certificates': {
        'task': 'apps.certificates.tasks.cleanup_expired_certificates',
        'schedule': 300.0,  # Cada 5 minutos
    },
    'validate-certificate-cache': {
        'task': 'apps.certificates.tasks.validate_certificate_cache',
        'schedule': 3600.0,  # Cada hora
    },
    'preload-missing-certificates': {
        'task': 'apps.certificates.tasks.preload_missing_certificates',
        'schedule': 1800.0,  # Cada 30 minutos
    },
}

# ==========================================
# CONFIGURACIÓN DE ARCHIVOS
# ==========================================

# Tamaño máximo de archivos de certificados
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Handlers de upload seguros
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# ==========================================
# CONFIGURACIÓN ADICIONAL DE DEBUG
# ==========================================

if DEBUG:
    # Logging más detallado en desarrollo
    LOGGING['loggers']['apps.certificates']['level'] = 'DEBUG'
    LOGGING['loggers']['apps.sri_integration.services.global_certificate_manager']['level'] = 'DEBUG'
    
    # Agregar handler de debug si necesario
    LOGGING['handlers']['debug'] = {
        'level': 'DEBUG',
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    }

# ==========================================
# CREAR DIRECTORIOS NECESARIOS
# ==========================================

# Crear directorios de logs y storage
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
os.makedirs(BASE_DIR / 'storage' / 'certificates', exist_ok=True)

# Configurar permisos seguros para certificados
cert_dir = BASE_DIR / 'storage' / 'certificates'
if cert_dir.exists():
    os.chmod(cert_dir, 0o700)  # Solo acceso para el propietario

# ==========================================
# SIGNALS PARA TOKEN AUTHENTICATION - MOVIDO A apps.py
# ==========================================

# NOTA: Los signals para auto-crear tokens se manejan en apps/users/apps.py
# para evitar problemas de AppRegistryNotReady durante el startup

# ==========================================
# MENSAJES DE CONFIGURACIÓN
# ==========================================

print("✅ Settings VENDO_SRI configurado con OAuth, Token Authentication y Session Timeout")
print(f"DEBUG: {DEBUG}")
print(f"SITE_ID: {SITE_ID}")
print(f"AUTH_USER_MODEL: {AUTH_USER_MODEL}")
print(f"SESSION_TIMEOUT: {SESSION_COOKIE_AGE} segundos ({SESSION_COOKIE_AGE // 60} minutos)")

# Mensajes de Token Authentication
print("🔑 Token Authentication configurado:")
print(f"   Auto-crear tokens: {AUTO_CREATE_TOKENS}")
print(f"   Token expira: {TOKEN_EXPIRES or 'Nunca'}")
print(f"   Auto-regenerar: {AUTO_REGENERATE_TOKEN_ON_LOGIN}")

# Mensajes de GlobalCertificateManager
print("🔐 GlobalCertificateManager configurado:")
print(f"   Auto-preload: {CERTIFICATE_AUTO_PRELOAD}")
print(f"   Cache timeout: {CERTIFICATE_CACHE_TIMEOUT} segundos")
print(f"   Max certificates: {MAX_CERTIFICATES_CACHE}")
print(f"   Auto-cleanup: {CERTIFICATE_AUTO_CLEANUP}")
print(f"   Cleanup interval: {CERTIFICATE_CLEANUP_INTERVAL} segundos")

if DEBUG:
    print("🚀 Modo desarrollo - Configuración optimizada para testing")
else:
    print("🏭 Modo producción - Configuración optimizada para performance")

# ==========================================
# TESTSERVER PARA TESTING
# ==========================================

ALLOWED_HOSTS.append("testserver")